version: "3.9"

services:
  hypergalaxy:
    container_name: hypergalaxy
    build:
      context: .
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on: 
      - pgsql
  
  pgsql:
    container_name: pgsql
    image: postgres:16.2-alpine3.19
    env_file:
      - .env

