# Generated by Django 5.0.2 on 2024-02-29 19:57

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa', models.ImageField(upload_to='')),
                ('titulo', models.CharField(max_length=68)),
                ('sumario', models.TextField(max_length=120)),
                ('categorias', models.CharField(choices=[('N', 'Notícias'), ('S', 'Social Mídia'), ('P', 'Programação')], default='N', max_length=1)),
                ('slug', models.CharField(max_length=120)),
                ('conteudo', django_ckeditor_5.fields.CKEditor5Field()),
                ('publicado', models.BooleanField(default=True)),
                ('destaque', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
