# Generated by Django 5.0.2 on 2024-02-17 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=255)),
                ('instagram', models.CharField(max_length=168)),
                ('facebook', models.CharField(max_length=168)),
                ('linkedin', models.CharField(max_length=168)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=68)),
                ('capa', models.ImageField(upload_to='')),
                ('descricao', models.TextField()),
                ('publicado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagesProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='')),
                ('descricao', models.CharField(max_length=55)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypergalaxy.projeto')),
            ],
        ),
    ]
