# Generated by Django 5.0.2 on 2024-02-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypergalaxy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='categoria',
            field=models.CharField(choices=[('U', 'UX/UI Design'), ('F', 'Front-end'), ('B', 'Back-end')], default='U', max_length=1),
        ),
    ]
