# Generated by Django 5.0.2 on 2024-02-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypergalaxy', '0003_alter_projeto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='categoria',
            field=models.CharField(choices=[('W', 'Web Design'), ('B', 'Branding'), ('D', 'Desenvolvimento'), ('M', 'Marketing')], default='W', max_length=1),
        ),
    ]
